apiVersion: apps/v1
kind: Deployment
metadata:
    name: auth-deployment
spec:
    replicas: 3
    selector:
        matchLabels:
            app: auth
    template:
        metadata:
            labels:
                app: auth
            annotations:
                prometheus.io/scrape: 'true'
                prometheus.io/path: /metrics
                # prometheus.io/port: '8080'
                prometheus.io/port: '9100'
        spec:
            containers:
                - image: pushpakant/auth
                  name: auth
                  ports:
                      - containerPort: 3000
